### PR TITLE
Fix incorrect colors in SCSS file

### PR DESCRIPTION
**Pull request by nielsenramon**
screen shot 2016-01-14 at 20 30 39

https://github.com/simurai/duotone-syntax/issues/9

Let me know what you think @simurai should fix all issues I encountered in SCSS.

### CODE REVIEW

**Comment by nielsenramon** [comment]
@simurai Any chance this can be merged? :)

**Comment by simurai** [comment]
Tested with the `scss` sample from @smlombardi's original issue: https://github.com/simurai/duotone-dark-earth-syntax/issues/1

``` scss
.class {
  color: rgba(255, 255, 255, 1);
  transition: all .1s linear;
  transform: scale(1.02) translateY(-2px);
}
```

screen shot 2016-01-25 at 8 35 08 pm

It feels a bit too strong. Maybe the punctuations could stay weak and functions could use the `uno` hue so they differentiate next to the numbers. Like:

``` less
.property-value {
  .duo-1();
  .function {
    .uno-2();
  }
  .punctuation {
    .uno-4();
  }
}
.variable.parameter.url {
  .duo-1();
}
```

screen shot 2016-01-25 at 9 25 24 pm

**Comment by nielsenramon** [comment]
@simurai I prefer your proposal. Much better :+1:

**Comment by nielsenramon** [comment]
@simurai I changed it to your example. However like this, the property is not the same like the LESS alternative. Don't you want it to reflect that more and turn it up a notch?

**Comment by smlombardi** [comment]
@nielsenramon It's up to @simurai but I wouldn't be troubled if the LESS and SCSS colors were slightly different.  Most of us use one or the other, and certainly wouldn't compare side by side.  As long as each looks optimal.

**Comment by simurai** [comment]
Ya, would be nice if they match, but yeah.. not a super strict rule.

So we could make `function`s in Less also use `uno-2`, but it looks pretty flat when using variables:

screen shot 2016-01-31 at 12 55 45 pm

So maybe use `uno-3` for functions in Sass.

screen shot 2016-01-31 at 4 30 38 pm

**Comment by nielsenramon** [comment]
@simurai It looks flat with `uno-2` but with `uno-3` it looks even more flat to me. The function is equally important as its value for me. It's up to you!

**Comment by simurai** [comment]
Maybe the whole "only using 7 shades" is reaching its limits. For `2.0` we could have 2 strongly saturated colors for each hue and then 4 (or more) mostly unsaturated mono colors.

screen shot 2016-02-07 at 1 50 16 pm

Anyways.. in the meantime.. I'm ok, either way. So let's merge this. :+1: Thanks!

**Comment by nielsenramon** [comment]
@simurai Sounds like a great idea, it indeed felt a bit to limited. Looking forward!

**Pull request merged**
